### PR TITLE
fix(encryption): unlock opens folder immediately without second click (#355)

### LINKED ISSUE #355: bug(encryption): unlocking a folder requires a second click to open if it was expanded before locking
## Problem

Entsperrt man einen zuvor verschlüsselten Ordner via Passwort-Modal, öffnet er sich nicht direkt. Ein zweiter Klick ist nötig, damit der Ordner aufklappt.

Erwartetes Verhalten: Nach erfolgreichem Unlock soll der Ordner direkt expandieren.

## Repro

1. Ordner `secret/` anlegen, expandieren.
2. Ordner verschlüsseln + sperren.
3. Ordner anklicken → Passwort-Modal öffnet sich.
4. Passwort eingeben → Unlock erfolgreich.
5. **Beobachtet:** Ordner bleibt zu. Erst ein zweiter Klick öffnet ihn.
6. **Erwartet:** Ordner öffnet sich direkt nach dem Unlock.

## Root cause

`TreeRow.handleClick` ruft nach erfolgreichem Unlock `onToggleExpand(row)` auf. `onToggleExpand` kippt den Zustand basierend auf `treeState.expanded.includes(row.relPath)`.

`lockFolder` entfernt den Ordner **nicht** aus `treeState.expanded` — war der Ordner vor dem Sperren expandiert, steht sein `relPath` noch in der Expanded-Menge. Toggle nach Unlock kollabiert den Ordner also, statt ihn zu öffnen. Erst der zweite Klick expandiert wieder.

## Fix

Neuer Prop `onEnsureExpanded` an `TreeRow` — idempotenter Guaranteed-Expand. Sidebar mappt das auf `setExpanded(relPath, absPath, true)` (existiert bereits, lädt Kinder + fügt zu expanded hinzu, wenn nicht vorhanden). Der Unlock-Success-Callback nutzt `onEnsureExpanded` statt `onToggleExpand`.

## Affected

- \`src/components/Sidebar/TreeRow.svelte\` — neuer Prop, \`handleClick\` nutzt ihn im Unlock-Callback
- \`src/components/Sidebar/Sidebar.svelte\` — Prop-Wiring zu \`setExpanded(..., true)\`
- \`src/components/Sidebar/__tests__/TreeRowUnlockExpand.test.ts\` — neue Regression-Tests

## Acceptance

- [ ] Unlock eines zuvor expandierten Ordners öffnet ihn direkt (kein zweiter Klick)
- [ ] Unlock eines nie-expandierten Ordners öffnet ihn ebenfalls direkt
- [ ] Bestehende Toggle-Interaktionen (Chevron, Leerzeichen, Context-Menu "New file here") unverändert
- [ ] Vitest-Regression für beide Unlock-Pfade

### PR DESCRIPTION
**Pull request by herox215**
## Summary

- Unlocking a folder that had been expanded before being locked no longer requires a second click — it opens immediately.
- Adds an idempotent `onEnsureExpanded` prop to `TreeRow`, wired to the Sidebar's existing `setExpanded(relPath, absPath, true)`.
- Unlock-success path now routes through ensure-expand instead of toggle.

Closes #355.

## Root cause

`TreeRow.handleClick`'s unlock-success callback called `onToggleExpand(row)`. `onToggleExpand` toggles based on `treeState.expanded.includes(row.relPath)`. Locking does **not** prune the expanded set, so a previously-expanded folder stayed in `treeState.expanded` while locked; toggling after unlock collapsed it instead of opening it.

## Test plan

- [x] `src/components/Sidebar/__tests__/TreeRowUnlockExpand.test.ts` — new regression: asserts click on locked folder opens unlock modal (not toggle), and that the success callback calls `onEnsureExpanded`, not `onToggleExpand`.
- [x] `npx vitest run src/components/Sidebar/` — 15 files, 31 tests green.
- [ ] Manual UAT: create folder, expand it, encrypt + lock, click → enter password → folder opens directly (no second click).
- [ ] Manual UAT: never-expanded locked folder — unlock opens it directly.
- [ ] Manual UAT: chevron toggle, context-menu "New file here", keyboard (Space/Enter) still behave as before.

### CODE REVIEW

File: src/components/Sidebar/TreeRow.svelte [hunk 1]
```diff
@@ -54,6 +54,13 @@
     onSelect: (path: string) => void;
     onOpenFile: (path: string) => void;
     onToggleExpand: (row: FlatRow) => void | Promise<void>;
+    /**
+     * Guaranteed-expand (idempotent). Use when the caller needs the
+     * folder open regardless of its current expanded state — e.g. after
+     * unlock, or after creating a child, where a plain toggle would
```
Comment (herox215) [inline src/components/Sidebar/TreeRow.svelte]: The prop doc lists "after creating a child" as a use-case for `onEnsureExpanded`, but `handleNewFileHere`, `handleNewCanvasHere`, and `handleNewFolderHere` (lines 302/316/329) still call `onToggleExpand({ ...row, expanded: false })`. `onToggleExpand` decides expand-vs-collapse by reading `treeState.expanded.includes(row.relPath)` — the `expanded` field on the row object is irrelevant. If the folder is already in the expanded set, all three handlers will collapse it after creating the child, which is the same regression this PR fixes for unlock. Either migrate those three to `onEnsureExpanded` in this PR, or remove "after creating a child" from the doc so the comment does not falsely advertise a fix that does not exist.

— Aristotle

File: src/components/Sidebar/TreeRow.svelte [hunk 2]
```diff
@@ -132,18 +140,13 @@
...
+      // was locked (locking doesn't prune the expanded set), forcing
+      // a second click to re-open it.
       if (isLocked) {
         openUnlockModal(row.path, row.name, async () => {
-          // The store swap + tree refresh run asynchronously after
-          // the unlock event; yield the microtask queue so the
-          // refreshed row is the one we toggle.
-          await Promise.resolve();
-          await onToggleExpand(row);
+          await onEnsureExpanded(row);
```
Comment (herox215) [inline src/components/Sidebar/TreeRow.svelte:162]: `onEnsureExpanded` is called from the unlock callback before `treeRefreshStore.requestRefresh()` fires (see `encryptedFoldersStore.ts` line 200: refresh is chained after `scheduleRefresh().then(...)`). `setExpanded` calls `loadFolder` when `!childrenLoaded`. The `treeRefreshStore` pulse then runs `invalidateAllFolders() + loadRoot()` in Sidebar, which wipes `folders` and triggers a second `loadFolder` for the same path concurrently. Two overlapping `listDirectory` IPC calls will race; the second sets `childrenLoaded = true` over whatever the first wrote. This is not a correctness bug today (both calls return the same data), but the old `await Promise.resolve()` at least let the `encrypted_folders_changed` event land and the row to be reconstructed with `encryption: "unlocked"` before expanding. Removing that yield means `onEnsureExpanded` is called while the row still carries the locked snapshot — does `loadFolder` proceed even when `DirEntry.encryption` is still `"locked"` on the backend-returned entry? If the backend requires an explicit unlock before `list_directory` returns children, this expansion fires too early and produces an empty folder until the second load from the refresh pulse completes.

— Aristotle

File: src/components/Sidebar/__tests__/TreeRowUnlockExpand.test.ts [hunk 3]
```diff
@@ -0,0 +1,124 @@
...
+    const row = container.querySelector(".vc-tree-row") as HTMLElement;
+    row.click();
+    await tick();
+
+    expect(openUnlockModal).toHaveBeenCalledTimes(1);
+    expect(openUnlockModal.mock.calls[0][0]).toBe(`${VAULT}/secret`);
+    expect(props.onToggleExpand).not.toHaveBeenCalled();
+  });
+
+  it("calls onEnsureExpanded (not onToggleExpand) on successful unlock", async () => {
```
Comment (herox215) [inline src/components/Sidebar/__tests__/TreeRowUnlockExpand.test.ts]: The test only verifies that `onEnsureExpanded` is wired in place of `onToggleExpand` — both props are `vi.fn()` mocks, so `setExpanded` is never exercised. The critical regression path (folder in `treeState.expanded` → lock → unlock → must stay open) is not asserted. A test that actually catches that regression must render `Sidebar` with a pre-populated `treeState.expanded` containing the folder`s `relPath`, simulate lock then unlock, and assert `row.expanded === true` in the resulting flat rows — not just that a mock callback was invoked. As written this test would have passed on the original buggy code if `onToggleExpand` were simply renamed to `onEnsureExpanded`.

— Aristotle

File: src/components/Sidebar/__tests__/TreeRowUnlockExpand.test.ts [hunk 4]
```diff
@@ -0,0 +1,124 @@
...
+    onSelect: vi.fn(),
+    onOpenFile: vi.fn(),
+    onToggleExpand: vi.fn(),
+    onEnsureExpanded: vi.fn(),
+    onRefreshFolder: vi.fn(),
+    onPathChanged: vi.fn(),
+  };
+}
+
+describe("TreeRow locked-folder unlock flow (#354 follow-up)", () => {
```
Comment (herox215) [inline src/components/Sidebar/__tests__/TreeRowUnlockExpand.test.ts]: Describe block references `#354 follow-up` but this PR fixes issue #355. Wrong ticket number.

— Aristotle

File: src/components/Sidebar/TreeRow.svelte [hunk 5]
```diff
@@ -130,20 +141,25 @@
...
+      //      (locking does not prune the expanded set), forcing
+      //      a second click to re-open it.
       if (isLocked) {
         openUnlockModal(row.path, row.name, async () => {
-          // The store swap + tree refresh run asynchronously after
-          // the unlock event; yield the microtask queue so the
-          // refreshed row is the one we toggle.
-          await Promise.resolve();
-          await onToggleExpand(row);
+          const parent = parentOf(row.path) ?? getVaultRoot();
```
Comment (herox215) [inline src/components/Sidebar/TreeRow.svelte:160]: `parentOf` uses `lastIndexOf("/")`, but on Windows `entry_path.to_string_lossy()` in `tree.rs:166` emits native backslashes — `DirEntry.path` in JS therefore contains `\` separators on Windows. For a top-level encrypted folder (`C:\Vault\secret`) there is no `/` in the path, so `lastIndexOf("/")` returns -1 and the guard `if (i <= 0) return null` fires. `getVaultRoot()` is then the fallback, but only if it returns non-null. If the store is uninitialized that is also null, and `if (parent) await onRefreshFolder(parent)` silently skips the refresh — expanding into still-locked children. Fix: normalise `absPath` with `.replace(/\\/g, "/")` before the `lastIndexOf`, matching the pattern already used in `vaultPath.ts` and `openFileAsTab.ts`.

— Aristotle

File: src/components/Sidebar/TreeRow.svelte [hunk 6]
```diff
@@ -296,7 +312,7 @@
     closeContextMenu();
     try {
       const newPath = await createFile(row.path, "");
-      await onToggleExpand({ ...row, expanded: false });
+      await onEnsureExpanded(row);
```
Comment (herox215) [inline src/components/Sidebar/TreeRow.svelte]: `onEnsureExpanded` fires before `onRefreshFolder` here, the opposite of the unlock path at line 161-162. For the "new file/folder here" context menu entries this order is harmless in practice (the folder is not encrypted, so `flattenTree` descends regardless), but it is a semantic inconsistency that makes the unlock ordering look like a deliberate exception when it is actually the invariant. Consider reversing to `refresh → ensure` here too, or add a comment explaining why the unlock order does not apply to this call site.

— Aristotle

File: src/components/Sidebar/__tests__/SidebarUnlockKeepsExpanded.test.ts [hunk 7]
```diff
@@ -0,0 +1,172 @@
...
+      return [];
+    });
+
+    render(Sidebar, { props: makeProps() });
+
+    // Drain initial mount + load.
+    for (let i = 0; i < 15; i += 1) { await Promise.resolve(); await tick(); }
+
+    // Click the locked folder → opens the unlock modal (not toggle).
+    const el = document.querySelector(
```
Comment (herox215) [inline src/components/Sidebar/__tests__/SidebarUnlockKeepsExpanded.test.ts]: `.vc-tree-row` never receives a `data-path` attribute (confirmed at `TreeRow.svelte:488-495`), so `document.querySelector(.vc-tree-row[data-path="..."])` always returns `null` and the fallback text-match branch always runs. The primary selector is dead. Remove it and the comment that apologises for it; just use the text-match directly.

— Aristotle
