### PR TITLE
fix(sidebar): rename cascade dialog races with watcher tree re-flatten (#378)

### LINKED ISSUE #378: rename-cascade dialog races with watcher tree re-flatten
## Repro

1. Open a vault with at least one note that has backlinks (e.g. \`Welcome.md\` referenced by \`[[Welcome]]\` from other files).
2. Right-click the note in the sidebar → Rename.
3. Type a new name and press Enter.

## Observed

The note is renamed on disk and in the tree, but the cascade-confirmation dialog (\"N Links in M Dateien werden aktualisiert. Fortfahren?\") never appears, so the backlinks are never rewritten — they end up dangling.

## Root cause

\`InlineRename.handleConfirm\` calls \`renameFile()\` IPC. The disk rename triggers the watcher, which flattens the tree and re-renders \`Sidebar\`. The \`{#each}\` block keys rows by \`row.path\`, so the renamed row destroys the original \`TreeRow\` and mounts a new one. But the \`renameFile\` promise was awaited inside the original \`TreeRow\`'s \`InlineRename\` component — when it resolves and calls \`onConfirm\`, the closure mutates \`pendingRename\` on a now-unmounted component. The new \`TreeRow\` doesn't carry that state, so the dialog never paints.

Direct IPC probing confirms \`rename_file\` correctly returns \`linkCount: 3\` for the test fixture — the backend is fine; the regression is purely in per-row state ownership.

## Fix candidates

1. **Lift \`pendingRename\` to \`Sidebar\`.** Single owner survives row remount. Cleanest architecturally.
2. **Delay the tree re-flatten until after \`pendingRename\` is committed.** Fragile — couples sidebar refresh to a sibling component's transient state.
3. **Hold the disk rename until the user confirms in the dialog.** Changes UX (rename-then-confirm-cascade → confirm-cascade-then-rename).

Recommendation: (1).

## Test

\`e2e/specs/rename-cascade.spec.ts\` is currently \`describe.skip\` with a pointer back here. The Vitest unit suite in \`commands/links::tests\` still covers the rename regex (\`#62\` left those tests passing for \`#H\` and \`^id\` suffix preservation).

### PR DESCRIPTION
**Pull request by herox215**
Fixes #378.

## Summary
- Lift `pendingRename` / `pendingMove` cascade state from per-row `TreeRow` up to `Sidebar`. The Sidebar is the single component that survives the watcher-driven tree re-flatten — per-row ownership lost the state the moment `loadRoot` re-keyed `{#each}`, so the cascade-confirm dialog never painted and backlinks ended up dangling.
- `TreeRow` hands the cascade request up via two new callback props (`onRequestRenameCascade` / `onRequestMoveCascade`) the moment the IPC await resolves — *synchronously*, no further `await`. The original `getBacklinks` call (the second await that crossed the unmount window for renames) now runs on Sidebar's always-mounted lifetime instead of TreeRow's per-row one.
- Cascade dialogs now render at Sidebar level. `aria-labelledby` is a stable `rename-heading` / `move-heading` (no per-row suffix) since only one dialog can be open at a time. The existing prefix-match selectors keep working.
- Modal precedence: an incoming cascade request is ignored if either `pendingRename` or `pendingMove` is already set — single-modal expectation.

## Why per-row was wrong
1. User confirms inline rename → `renameFile` IPC mutates disk
2. Backend emits synthetic `FILE_CHANGED_EVENT(kind: rename)` (because `write_ignore` suppressed the natural one)
3. Sidebar's watcher handler runs `invalidateAllFolders()` + `loadRoot()` → `flatRows` recomputes → `{#each windowRows as { row } (row.path)}` re-keys → original `TreeRow` for the renamed file unmounts under the old path, new one mounts under the new path
4. `InlineRename`'s post-IPC continuation calls `onConfirm` on a closure pointing at the dead `TreeRow` instance → mutating `pendingRename` on a destroyed component → dialog never paints

## Test plan
- [x] New Vitest unit `Sidebar.cascade.test.ts` simulates the race: triggers a rename via the IPC mock, fires the watcher event programmatically mid-flight, asserts the dialog stays mounted *and* the original row is gone (`{#each}` re-keyed) while the renamed row is mounted under the new path. Fails on `main`, passes on this branch.
- [x] All 18 sidebar Vitest files green (41 tests).
- [x] `svelte-check` clean for the Sidebar workspace.
- [ ] e2e `rename-cascade.spec.ts` un-skipped — verify on UAT (WebDriver was not running locally).
- [ ] UAT: open a vault with a note that has 1+ backlinks, rename via context menu, confirm dialog appears with German body, click *Aktualisieren* → backlinks rewritten, no dangling links remain.

## Files
- `src/types/sidebar.ts` (new) — `RenameCascadeRequest` / `MoveCascadeRequest` / `PendingRename` / `PendingMove`
- `src/components/Sidebar/Sidebar.svelte` — owns cascade state + dialogs + `getBacklinks`
- `src/components/Sidebar/TreeRow.svelte` — drops cascade state + dialogs, adds two callback props
- `src/components/Sidebar/__tests__/Sidebar.cascade.test.ts` (new) — regression guard
- `e2e/specs/rename-cascade.spec.ts` — un-skipped, comment updated
- 4 existing TreeRow tests — added the two new required props to fixtures

### CODE REVIEW

File: src/components/Sidebar/TreeRow.svelte [hunk 1]
```diff
@@ -444,14 +419,14 @@
     }
 
     if (linkCount > 0) {
-      pendingMove = {
+      onRequestMoveCascade({
```
Comment (herox215) [inline src/components/Sidebar/TreeRow.svelte]: The `await getBacklinks(sourceRelPath)` call (9 lines above, in `handleDrop`) is still there before this `onRequestMoveCascade` call — the identical unmount race that was fixed for rename survives for drag-drop. A watcher event can re-key `{#each}` during that await and destroy this `TreeRow` instance before this line is reached. Move the `getBacklinks` call into `handleRequestMoveCascade` in Sidebar (same pattern used by `handleRequestRenameCascade`), drop `fileCount` from `MoveCascadeRequest`, and pass `linkCount` alone from `handleDrop`.

— Aristotle

File: src/components/Sidebar/Sidebar.svelte [hunk 2]
```diff
@@ -519,6 +541,96 @@
...
+
+  function handleRequestMoveCascade(req: MoveCascadeRequest) {
+    if (pendingRename || pendingMove) return;
+    pendingMove = req;
+  }
+
+  async function confirmRenameWithLinks() {
+    if (!pendingRename) return;
+    const { oldPath, newPath, oldRelPath, newRelPath } = pendingRename;
+    pendingRename = null;
```
Comment (herox215) [inline src/components/Sidebar/Sidebar.svelte]: `pendingRename = null` is set before `await updateLinksAfterRename` — the modal guard (`if (pendingRename || pendingMove) return`) is cleared before the async work finishes. A rapid second rename that lands during the `updateLinksAfterRename` await will pass the guard and open a second dialog, potentially triggering concurrent link rewrites. Null the state only after the await resolves (or keep a separate boolean `isConfirmInFlight` for the guard).

— Aristotle

File: src/components/Sidebar/__tests__/Sidebar.cascade.test.ts [hunk 3]
```diff
@@ -0,0 +1,194 @@
...
+}
+
+describe("Sidebar rename cascade survives tree re-flatten (#378)", () => {
+  beforeEach(() => {
+    vi.stubGlobal("localStorage", makeLocalStorage());
+    capturedFileChangeHandler = null;
+    vaultStore.reset();
+    bookmarksStore.reset();
+    vaultStore.setReady({ currentPath: VAULT, fileList: [], fileCount: 0 });
+    vi.clearAllMocks();
```
Comment (herox215) [inline src/components/Sidebar/__tests__/Sidebar.cascade.test.ts:119]: `vi.clearAllMocks()` resets the `updateLinksAfterRename` spy whose `.mockResolvedValue(...)` was set in the `vi.mock` factory at line 18 — after this line that mock resolves `undefined`. The current test does not exercise the confirm path so this is latent, but a follow-up that clicks Aktualisieren will get a spurious throw on `result.updatedPaths`. Re-apply the return value here in `beforeEach` alongside the other per-test mocks, or replace `clearAllMocks()` with `resetAllMocks()` which resets call history but keeps implementations.

— Aristotle

File: src/components/Sidebar/Sidebar.svelte [hunk 4]
```diff
@@ -519,6 +541,150 @@
...
+  // #378 — cascade-request handlers from TreeRow. The row hands the request
+  // up the moment the IPC await resolves (synchronously, no further await),
+  // so the closure capture cannot race the row's unmount. Sidebar then runs
+  // any post-IPC work (getBacklinks for fileCount, dialog rendering,
+  // updateLinksAfterRename on confirm) on its own always-mounted lifetime.
+  async function handleRequestRenameCascade(req: RenameCascadeRequest) {
+    // Modal precedence: ignore overlapping cascade requests. Only one dialog
+    // open at a time. The user can re-trigger the suppressed action after
+    // resolving the first dialog.
+    if (pendingRename || pendingMove) return;
```
Comment (herox215) [inline src/components/Sidebar/Sidebar.svelte]: The re-entrancy guard is checked at line 553 but `pendingRename` is not set until line 561, after the `getBacklinks` await. A second rename triggering `handleRequestRenameCascade` during that await will pass the guard — both calls read `pendingRename === null` — and the final two writes race to set `pendingRename`, leaving a second dialog (or a silently overwritten first one). Fix: set a sentinel synchronously before the await, e.g. set `pendingRename = { ...req, fileCount: 1 }` (or a dedicated `inflightRename` boolean) before the `try`, then overwrite with the resolved `fileCount` after.

— Aristotle

File: src/components/Sidebar/Sidebar.svelte [hunk 5]
```diff
@@ -519,6 +541,150 @@
...
+      fileCount = new Set(backlinks.map((b) => b.sourcePath)).size || 1;
+    } catch {
+      /* fall back to the linkCount/1 default */
+    }
+    pendingRename = { ...req, fileCount };
+  }
+
+  async function handleRequestMoveCascade(req: MoveDropRequest) {
+    // Modal precedence — same rule as rename cascade.
+    if (pendingRename || pendingMove) return;
```
Comment (herox215) [inline src/components/Sidebar/Sidebar.svelte]: Same re-entrancy window as `handleRequestRenameCascade`: the guard fires at line 566 but `pendingMove` is not written until line 590 (or the direct-move path at line 605), after the `getBacklinks` await at line 582. Two drops in rapid succession both read `pendingMove === null` and both proceed; the second `getBacklinks` call overlaps the first pipeline and can double-fire `moveFile`. Set a sentinel before the await.

— Aristotle

File: src/components/Sidebar/__tests__/Sidebar.cascade.test.ts [hunk 6]
```diff
@@ -0,0 +1,210 @@
...
+    expect(body.textContent ?? "").toMatch(/3\s+Links?\s+in\s+\d+\s+Dateien/);
+
+    // Sanity: the row that owned the original `pendingRename` is no longer
+    // mounted under the old path — the {#each} re-keyed it. Without the fix,
+    // this is exactly the moment the dialog would disappear.
+    const oldRow = container.querySelector(`[data-tree-row="${VAULT}/Welcome.md"]`);
+    expect(oldRow).toBeNull();
+    const newRow = container.querySelector(`[data-tree-row="${VAULT}/Welcome Renamed.md"]`);
+    expect(newRow).toBeTruthy();
+  });
```
Comment (herox215) [inline src/components/Sidebar/__tests__/Sidebar.cascade.test.ts:209]: The test stops after asserting the dialog is visible but never clicks "Aktualisieren" — `confirmRenameWithLinks`, `updateLinksAfterRename`, and the `finally { pendingRename = null }` path are all unexercised. The `finally` block was the core of issue #2 in the first review; it now has no regression coverage. Add a second `it` that clicks the confirm button, drains microtasks, and asserts: (a) `updateLinksAfterRename` was called once with the correct args, (b) the dialog is gone from the DOM.

— Aristotle
